### ISSUE TITLE
Design choices regarding function expansion, application, and substitution

### ISSUE THREAD

**Issue by banacorn** [scmlab/gcl#13]
```
let P x y = x + y + z
z := 1
{ P 2 3 }
```

The program above would result in such a proof obligation:

```
True => P [1 / z] 2 3
```

When `P` gets clicked, `P [1 / z] 2 3` could become:

1. `(\x -> \y -> x + y + z) [1 / z] 2 3` (only expanding `P`, the current approach)
2. `(x + y + z) [1 / z] [2 / x] [3 / y]` (replacing function application with substitution)
3. `2 + 3 + 1` (full reduction)

Personally, I prefer *Option 2*, because this allows us to treat substitution and function application in a more uniform way. And we already know how to let users trigger substitutions.

We could also opt for *Option 1*, as long as we can figure out a way to trigger function applications (perhaps by clicking on one of the arguments).
Suppose that the whole expression have been reduced to `(\x -> \y -> x + y + 1) 2 3` and the user clicked on the first argument (`2`), the expression could become:

1. `(\y -> x + y + 1) [2 / x] 3` (replacing function application with substitution)
2. `(\y -> 2 + y + 1) 3` (reduction)

Both seem fine, but if the user chooses to clicked on the **second** argument (`3`) instead, there are 2 options regarding how to deal with the first argument (or any argument that comes before the clicked one), we could:

1. "force" the arguments before it:
  1. `(x + y + 1) [2 / x] [3 / y]` (replacing function application with substitution)
  2. `2 + 3 + 1` (full reduction)

2. "skip" the arguments before it:
  1. `(\x -> x + y + 1) [3 / y] 2` (replacing function application with substitution)
  2. `(\x -> x + 3 + 1) 2` (partial reduction)

I'm not sure if the "skipping" option is viable anyway

**Comment by scmu** [comment]
Regarding how `P [1 / z] 2 3` should be reduced, when `P x y = x + y + z`. There is a missing option: `(\x -> \y -> x + y + 1) 2 3`. To get this, we expand `P` to lambda, then reduce the lambda. Or, in other words, we do a fill expansion of the sub-expression `P [1 / z]`.

The rationale for doing so is:
* suppose we implement Option 2. What would one do after one gets `(x + y + z) [1 / z] [2 / x] [3 / y]`? Almost definitely, one would click on `[1/z]` to get `(\x -> \y -> x + y + 1) 2 3`. The substitution will be expanded anyway.
* Similarly with Option 1: `(\x -> \y -> x + y + z) [1 / z] 2 3`. This expression does not help. 

The thing is that we expand expressions to see how it can be further manipulated. Consider `P x y = x * y * z` applied to the substitution `[z+1/z]`. 
* `(\x y -> x * y * z)[z+1/z]` does not mean much to me. 
* When I see `(\x y -> x * y * (z+1))`, I see `(*)` and `(+)` together. Then I can perhaps apply distributivity and get `(\x y -> x * y * z + x*y))`. This may help me to make some progress.

---

"as long as we can figure out a way to trigger function applications" -- we will need to fully expand the expression. As I said above, `(\x -> \y -> x + y + 1) expr1 expr2` is not useful. I need to see `expr1 + expr2 + 1` to see what further manipulation is possible.

(In fact that is why I don't mind doing a full expansion (up to a certain level).)

---

As for the last question I'd go for either 1 or 3. Note that it is not trivial forcing a substitution in the end alone : `P[e1/x][e2/y]` does not in general equal `P[e2/y][e1/x]`. Instead we have
```
P[e1/x][e2/y] = P[e2/y][e1[e2/y]/x]
```
The matter is more complicated when `e1` or `e2` themselves contain defined names. And partial evaluation is a whole area to explore.

**Comment by banacorn** [comment]
> suppose we implement Option 2. What would one do after one gets (x + y + z) [1 / z] [2 / x] [3 / y]? Almost definitely, one would click on [1/z] to get (\x -> \y -> x + y + 1) 2 3. The substitution will be expanded anyway.

Clicking on `[1/z]` in `(x + y + z) [1 / z] [2 / x] [3 / y]` should result in `(x + y + 1) [2 / x] [3 / y]`, because function application reduction is defined using substitution.

---

We could do option 3 (full expansion). However, since our functions are curried, the extent of full expansion of a function (i.e. arity) will have to be predetermined, before sending to the frontend for display. So that when the user clicked on a name, say `P`, the frontend knows which arguments to be send to the backend along with the function.
