### ISSUE TITLE
Allow the content of a Spec to be preserved after parsing

### ISSUE THREAD

**Issue by banacorn** [scmlab/gcl#21]
Stuff in between `[!  !]` is discarded after parsing, but I wish we can have it preserved for later use (spec refinement)

I've amended the abstract syntax and used `mempty` as a temporary placeholder.

https://github.com/scmlab/gcl/blob/2ccf037cb983d82d0632093ebe20affd6311d8e8/src/Syntax/Abstract.hs#L54

https://github.com/scmlab/gcl/blob/2ccf037cb983d82d0632093ebe20affd6311d8e8/src/Syntax/Concrete.hs#L116

@potsrevennil :pleading_face:

**Comment by potsrevennil** [comment]
Fixed~
