### ISSUE TITLE
Type error with "constant" predicates

### ISSUE THREAD

**Issue by scmu** [scmlab/gcl#40]
Consider the code:
```
var i, n : Int
    
let Q i = n ≥ 0
    
{ Q i }
```
While Q should be a predicate `Int -> Bool`, we get a type error
```
Cannot unify types3:11-16
Cannot unify: Bool
with        : Int
```
The location of the error is where `n ≥ 0` is.

Curiously it only happens with the presence of `Q i` in the post condition. The error goes away when we change it to `True`.

**Comment by potsrevennil** [comment]
This happened due to wrongly maintained state for generating fresh variables.
Should be fixed now.
