### ISSUE TITLE
Name capturing in substitution

### ISSUE THREAD

**Issue by scmu** [scmlab/gcl#41]
Capturing-avoid substitution was not implemented correctly. Sample program:
```
con f : Int -> Bool
var i, n : Int

let P n = ⟨ ∧ i : 0 ≤ i < n : f i ⟩

n := n + i
{ P n }
```
`P n [ n + i / n ]` (which is `P (n+i)`) gets expanded to  `⟨ ∧ i : 0 ≤ i < n + i  : f i ⟩`, while we should introduce fresh names and make it `⟨ ∧ _m0 : 0 ≤ _m0 < n + i : f _m0 ⟩` (or something prettier).

Note that the same problem happens with
```
con f : Int -> Bool
var i, n : Int

let P n = ⟨ ∧ i : 0 ≤ i < n : f i ⟩

{ P (n + i) }
```
where `P (n+i)` gets expanded to  `⟨ ∧ i : 0 ≤ i < n + i  : f i ⟩`.

**Comment by scmu** [comment]
The problem persists with 0.1.11. This is what I see after applying the substitution:
![Screen Shot 2021-06-23 at 7 09 26 PM](https://user-images.githubusercontent.com/11384501/123086896-8941d100-d456-11eb-8c13-51e21c513b0b.jpg)

**Comment by potsrevennil** [comment]
should be fixed by now!
