### ISSUE TITLE
Capture-avoiding substitution

### ISSUE THREAD

**Issue by banacorn** [scmlab/gcl#6]

**Comment by scmu** [comment]
Hope this is fixed now. Issue closed.

![Screen Shot 2020-10-02 at 4 23 56 PM](https://user-images.githubusercontent.com/11384501/94903050-c5e62a80-04cb-11eb-9985-3dee76e14042.jpg)

**Comment by scmu** [comment]
Still wrong -- `n` shouldn't be substituted below.

Will look into it.

![Screen Shot 2020-10-12 at 6 00 50 PM](https://user-images.githubusercontent.com/11384501/95733603-f5a7e600-0cb4-11eb-9827-9b396612f447.jpg)

**Comment by scmu** [comment]
Should be fixed now.
