### ISSUE TITLE
Erratic behaviour with spec displaying and filling (lexer branch)

### ISSUE THREAD

**Issue by scmu** [scmlab/gcl#61]
In the `lexer` branch, behaviour with spec displaying and filling is rather erratic now. Demonstrating with screen shots.

Say I start with this program:
![Screen Shot 2022-03-27 at 11 00 46 AM](https://user-images.githubusercontent.com/11384501/160264959-4998a1d6-9630-434d-bd0b-00f162bea81f.jpg)

If I type a `?` I get this. The `?` after the `[! ... !]` remains there.
![Screen Shot 2022-03-27 at 11 01 04 AM](https://user-images.githubusercontent.com/11384501/160264972-929952c1-8487-47dc-accd-fa6c697a3f43.jpg)

Deleting the `?` manually. Notice that the pre/postconditions of the spec are not displayed.
![Screen Shot 2022-03-27 at 11 01 13 AM](https://user-images.githubusercontent.com/11384501/160265007-b00167fb-90dc-4bba-aba5-ad17a5fa890a.jpg)

Now I try to type this into the spec and press `ctrl-c-r`:
![Screen Shot 2022-03-27 at 11 01 43 AM](https://user-images.githubusercontent.com/11384501/160265012-0aefda27-3269-4004-950a-8d4d4b9be7ca.jpg)
I get this:
![Screen Shot 2022-03-27 at 11 01 52 AM](https://user-images.githubusercontent.com/11384501/160265026-f86e81cf-7b10-487c-8a2f-8212e42dca20.jpg)

After some more tweaking I get this. Notice that the postcondition is displayed between `!` and `]`:
![Screen Shot 2022-03-27 at 11 03 00 AM](https://user-images.githubusercontent.com/11384501/160265038-895ea66c-6956-4e51-90cd-2cd4957aa757.jpg)

**Comment by geoffcysu** [comment]
It seems to be the conflict of definitions of token's range between the lexer and our range definition, documented in `Data.Loc.Range`. I altered the `TokStream`(to make the token's range fit our definition) in the `scan` function in `Syntax.Parser2.Lexer`, then it functions correctly.

**Comment by scmu** [comment]
It works alright now. Closing the issue.
