### ISSUE TITLE
Parsing problem with comment blocks

### ISSUE THREAD

**Issue by scmu** [scmlab/gcl#64]
Block comments (`{- ... -}`) cannot be parsed at all.
See several examples below.

One line:

![Screen Shot 2022-11-02 at 12 14 36 PM](https://user-images.githubusercontent.com/11384501/199394401-a16980d3-9a27-4f4c-b747-32fb7314931e.jpg)

Multilines:
![Screen Shot 2022-11-02 at 12 14 18 PM](https://user-images.githubusercontent.com/11384501/199394444-c11786c3-84bd-428b-add7-be77a267eeeb.jpg)

Multilines, indented:
![Screen Shot 2022-11-02 at 12 14 27 PM](https://user-images.githubusercontent.com/11384501/199394478-f3b0af25-08ba-43ff-96b3-30d00b9600cc.jpg)

Proof blocks appears to be fine...
![Screen Shot 2022-11-02 at 12 14 55 PM](https://user-images.githubusercontent.com/11384501/199394537-b6ba8e6d-4617-458b-b388-13846c3b76cb.jpg)

until you type a period (.) in the comment:
![Screen Shot 2022-11-02 at 12 15 05 PM](https://user-images.githubusercontent.com/11384501/199394599-6c5d8637-22eb-45e2-a204-bdef280bae23.jpg)

Note: I noticed the problem when I tried to write up a proof. I encountered the last case first, before I realized that parsing of ordinary comments are problematic too.

**Comment by jaiyalas** [comment]
Are they still errors? It works on my side. :thinking: 

Archlinux: 5.19.13-arch1-1
gcl: 0.3.11-ubuntu 
extension: 0.3.15

**Comment by scmu** [comment]
It was fixed. :) Closing the issue for now.
